export const projectData = {
  Pin: [
    {
      project_name: "Seekai.tool",
      link: "https://seekai.tools/ai-tools",
      date: "Nov 2023 - Present",
      role: "Full Stack Engineer Intern @ Nexa AI",
      techniques: [
        "HTML",
        " CSS",
        " JavaScript",
        " React",
        " Java(Spring)",
        " Python(Flask)",
        " Google Cloud Platform",
        " MongoDB",
      ],
      short_description:
        "Stability AI excels in open-source, community-driven AI for ethical and accessible image and text generation, democratizing AI across various industries. Four primary pages including AI Tools, GPTs, Ranking, and Blogs to help users quickly and efficiently find suitable AI tools among over 12,170 AI tools and nearly 5,000 GPTs.",
      tasks: [
        "Led the web development using <strong> HTML, CSS, and JavaScript</strong> (focusing on the <strong>React</strong> framework), ensuring effective mobile adaptation across various mobile devices. Generated data visualization section in detail pages to provide more reliable data of the AI Tools.",
        "Managed user data and product content in <strong>MongoDB</strong>, ensuring optimal data storage, integrity, and performance through effective manipulation, cleaning, and optimization techniques by using <strong>Python</strong>.",
        "Utilized <strong>Google Analytics</strong> for user behavior tracking and analysis, optimizing user journey paths, which led to over <strong>1,000</strong> customer visits and attracted <strong>943</strong> unique users within a month, resulting in a steady growth of the user base.",
        "Developed <strong>RESTful APIs</strong> for search engines and database interactions, implemented in <strong>Python (Flask) and Java (Spring)</strong>, integrated with frontend, and tested for performance.",
        "Collaborated with product managers on iterative product development, achieving a user engagement uplift by increasing the average page views to <strong>26.02</strong> per user, indicative of enhanced user stickiness and refined product details.",
      ],
      image_gallery: [
        "https://github.com/JiayingYu152/image-and-files/raw/5f69866b7d3deeeb9d6608b56fab7416669e67f4/ai%20tools%20page.png",
        "https://github.com/JiayingYu152/image-and-files/raw/5f69866b7d3deeeb9d6608b56fab7416669e67f4/ai%20tools%20detail%20page.png",
        "https://github.com/JiayingYu152/image-and-files/raw/5f69866b7d3deeeb9d6608b56fab7416669e67f4/Ranking%20page.png",
        "https://github.com/JiayingYu152/image-and-files/raw/5f69866b7d3deeeb9d6608b56fab7416669e67f4/ranking%20page%20mobile%20terminal.png",
        "https://github.com/JiayingYu152/image-and-files/raw/49925c59d3c18351fc482abeb587ea018197070b/seek_ai_tools_1.png",
      ],
      verification: "Product Hunt Verified: Nov 2023",
      verification_link: "https://www.producthunt.com/products/nexa-ai",
    },
    {
      project_name: "Personal Portfolio Website",
      link: "https://jiayingyu152.github.io/",
      date: "Jan 2024 - Present",
      role: "Website Designer and Responsible for Implementation",
      techniques: ["HTML", " CSS", " JavaScript", " formspre"],
      short_description:
        "A one-stop website to list all of my connection social media platform including <strong>Github, LinkedIn, Product Hunt, and Instagram</strong> so that people can know all of my experience here.",
      tasks: [
        "<a href=`https://github.com/JiayingYu152/JiayingYu152.github.io`>Github</a>: https://github.com/JiayingYu152/JiayingYu152.github.io ",
      ],
      image_gallery: [],
      verification: "",
      verification_link: "",
    },
  ],
  Professional: [
    {
      project_name: "Nexa.ai (website stopped in use)",
      link: "https://www.producthunt.com/products/nexa-ai",
      date: "Oct 2023 – Nov 2023",
      role: "Full Stack Engineer Intern @ Nexa AI",
      techniques: [
        "HTML",
        " CSS",
        " JavaScript",
        " React",
        " Python(Flask)",
        " Google Cloud Platform",
        " MongoDB",
      ],
      short_description:
        "Stage the perfect ecommerce photoshoot and generate an unlimited number of high resolution images on Nexa. Simply upload your product images, choose from 100+ of templates, customize models & scenes, and your photos are ready to use!",
      tasks: [
        "Developed a log project internally to capture user exposure and click actions at various stages, analyzing behavior profiles for website functionality optimization.",
        "Employed Google Analytics to track and analyze external user behavior, successfully capturing data on 1.3K users and 80K views, with an influx of <strong>1.3K</strong> new users and an average engagement time of <strong>11 minutes</strong> and <strong>10 seconds</strong> over the <strong>last 3 months</strong>.",
        "Conducted data processing and cleaning with <strong>Python</strong>, and organized data storage in <strong>MongoDB</strong> as well as on the <strong>Google Cloud Platform</strong>",
        "Conducted comprehensive feature testing to assess system reliability and adherence to project objectives, with a focus on evaluating the efficacy of various image-generating machine learning algorithms for optimal selection.",
      ],
      image_gallery: [
        "https://github.com/JiayingYu152/image-and-files/raw/49925c59d3c18351fc482abeb587ea018197070b/nexa_ai_2.png",
        "https://github.com/JiayingYu152/image-and-files/raw/49925c59d3c18351fc482abeb587ea018197070b/advanced-GA-certificate.png",
        "https://github.com/JiayingYu152/image-and-files/raw/49925c59d3c18351fc482abeb587ea018197070b/GA-certificate.png",
      ],
      verification: "Product Hunt Verified: Nov 2023",
      verification_link: "https://www.producthunt.com/products/nexa-ai",
      additional_information:
        "<strong>Google Analytics for Beginners Certification</strong>, <strong>Advanced Google Analytics Certification</strong>",
    },
    {
      project_name: "Apartment Management System",
      link: "https://youtu.be/ONMcdt2MSU0",
      date: "May 2023 – June 2023",
      role: "Backend Engineer",
      techniques: [
        "Java(Spring Boot & Spring Security)",
        " RESTFUL API",
        " MySQL",
        " AWS",
      ],
      short_description:
        "The Apartment Management System is an intuitive web platform that facilitates seamless interaction between tenants, property managers, and maintenance personnel. It includes a user-friendly dashboard for an overview of apartment affairs, a maintenance section for logging and tracking repair requests, a reservation system for amenities, an integrated payment portal for financial transactions, and a forum for community discussions.",
      tasks: [
        "Developed and implemented the backend services based on <strong>Spring Boot</strong> to facilitate tenant and manager access to amenities and service requests including reservation, payment, and other features using <strong>RESTful API</strong>.",
        "Partnered with the backend team in the end-to-end process from database design to code implementation.",
        "Implemented token-based server-side user authentication based on the <strong>Spring Security</strong>framework.",
        "Leveraged <strong>MySQL</strong> for efficient and reliable data storage in the database.",
      ],
      image_gallery: [
        "https://github.com/JiayingYu152/image-and-files/raw/49925c59d3c18351fc482abeb587ea018197070b/full-stack-certificate.png",
      ],
      verification: "",
      verification_link: "",
    },
    {
      project_name: "OrderEase",
      link: "",
      date: "Feb 2023 – March 2023",
      role: "Full Stack Engineer",
      techniques: [
        "Java(Spring Boot)",
        " JavaScript",
        " HTML & CSS",
        " React",
        " Node.js",
        " Hibernate",
        " AWS",
        " RESTFUL API",
        " ReactJS",
      ],
      short_description: "Spring and Hibernate-based Digital Ordering System",
      tasks: [
        "Implemented <strong>RESTful API</strong> via <strong>Spring MVC</strong> including registration, menu searching and ordering, checkout, etc.",
        "Utilized Hibernate to access and operate the data storage (menu, restaurants, etc).",
        "Provided authentication and authorization via <strong>Spring Security</strong> to protect the application from malicious attacks.",
        "Used the <strong>Spring</strong> framework core technologies to loosely decouple all the components in the application.",
        "Built the client side with <strong>ReactJS</strong> and <strong>Ant Design</strong> to allow users to add items to the shopping cart and place orders.",
      ],
      image_gallery: [],
      verification: "",
      verification_link: "",
    },
    {
      project_name: "RoomNet",
      link: "",
      date: "April 2023 – May 2023",
      role: "Full Stack Engineer",
      techniques: [
        "JavaScript",
        " Java(Spring Boot)",
        " React",
        " Google Cloud Platform",
        " MySQL",
        " Elasticsearch",
      ],
      short_description: "Digital Accommodation Booking Solution",
      tasks: [
        "Built a web application using <strong>React</strong>. Bootstrap the development with mature component library AntD.",
        "Implemented backend services based on <strong>Spring Boot</strong> to support stay upload, delete, search functionality.",
        "Used <strong>MySQL</strong> to store user-generated data and utilized <strong>Google Cloud Platform</strong> to store media files for update.",
        "Created geo index by <strong>Elasticsearch</strong> to support geo-based stay search based on user's selected locations.",
        "Deployed the backend service to Google App Engine for better scalability and reliability.",
      ],
      image_gallery: [],
      verification: "",
      verification_link: "",
    },
    {
      project_name: "MusicMingle",
      link: "",
      date: "March 2023 – April 2023",
      role: "Android Engineer",
      techniques: ["Kotlin", " Android", " RESTful API"],
      short_description: "Minimalist Spotify Favorite App",
      tasks: [
        "Designed a <strong>Kotlin</strong> Spotify favorite app by leveraging <strong>Android JetPack</strong> Library and Hilt Dependency Injection.",
        "Implemented the BottomBar & App Navigation using Jetpack Navigation component.",
        "Created a mock <strong>RESTful API</strong> json-server and used Retrofit to handle requests.",
        "Built the feed/album/favorite UI in Jetpack Compose following MVVM architecture.",
        "Integrated the Google Exoplayer to handle the global music playback.",
      ],
      image_gallery: [],
      verification: "",
      verification_link: "",
    },
    {
      project_name: "NFTrend: NFT Price Trend Visualization",
      link: "",
      date: "May 2023",
      role: "Frontend Engineer",
      techniques: ["JavaScript", " React", " Moralis NFT API"],
      short_description: "",
      tasks: [
        "Developed an NFT Price Visualization dashboard, utilizing <strong>React</strong> and <strong>JavaScript</strong>, providing users with a comprehensive search, view, and analysis platform for NFT assets.",
        "Leveraged the <strong>AntD UI</strong> Component Library for efficient client-side development, enhancing the user interface and user experience of the NFT dashboard.",
        "Integrated the <strong>Moralis NFT API</strong> for fetching relevant NFT data such as price, name, and description, thereby enriching the data available to users for decision making.",
        "Designed and implemented an intuitive NFT trade/price chart user interface using Rechart, enabling users to effortlessly visualize and understand NFT price fluctuations over time.",
      ],
      image_gallery: [],
      verification: "",
      verification_link: "",
    },
  ],
  Entrepreneurship: [
    {
      project_name: "EyeSnap (Our Team Won Bayer Challenge Global Champion)",
      link: "https://www.youtube.com/watch?v=RQdKQIvrKkc",
      date: "Oct 2022 – Dec 2022",
      role: "Technical Support, Product Designer",
      techniques: [
        "AI algorithm",
        " sensor data",
        " cloud computing",
        " platform encryption",
      ],
      short_description: "Vision Health Monitoring Glasses",
      tasks: [
        "<strong>Sensory data/Cloud computing/Database</strong>: We collect the sensor data from three sensors in glass frames. These raw data will be transmitted to the cloud database. We make cloud computing as our database carrier because we will input all of the AI algorithms into the cloud and all data computing and AI diagnosis technologies will be done in the cloud. Regarding the database, at the initial stage, we need to collect the medical history from the ophthalmology clinic and experiment; later, we would upload our experiment data to the cloud database. By combining both database and further data collection, we develop a database and diagnosis system more accurately and precisely. The reason why we are using AI algorithm and Cloud storage is to reduce the artificial risk of data leakage. Also, EyeSnap cares the data privacy issue as well. EyeSnap will apply the platform encryption algorithm to protect data security. Only by admitted by the users, these data would be transferred to ophthalmologist and third-party organizations.",
        "<strong>AI algorithm</strong>: Current AI algorithms, including ML and Deep Learning algorithms, can achieve over 82% diagnostic accuracy in glaucomatous VFs. The current research results came from some Glaucoma Hemifield Test (GHT) tests and pattern standard deviation (PSD). AI algorithm has been investigated and developed for automated glaucoma detection that can quickly process the retinal images and accurately detect glaucomatous damage on pathological tests compared to conventional methods. Also, the current AI algorithm can be used for diagnosing and grading cataracts. To sum up, the technological part of the AI algorithm is practical and feasible.",
      ],
      image_gallery: [
        "https://github.com/JiayingYu152/image-and-files/raw/e04654c7a2b4022cb96aa29a89b18505cd48d7ae/eyesnap_1.png",
        "https://github.com/JiayingYu152/image-and-files/raw/e04654c7a2b4022cb96aa29a89b18505cd48d7ae/eyesnap_2.png",
        "https://github.com/JiayingYu152/image-and-files/raw/e04654c7a2b4022cb96aa29a89b18505cd48d7ae/eyesnap_3.png",
      ],
      verification:
        "Bayer Challenge Global Champion in 2022 (video started 1:22)",
      verification_link: "https://www.youtube.com/watch?v=RQdKQIvrKkc",
    },
    {
      project_name: "Truck Space Optimization System (Project Stopped)",
      link: "",
      date: "Sep 2023 – Oct 2023",
      role: "Software Develop Engineering, Co-founder, Marketing",
      techniques: [],
      short_description: "",
      tasks: [
        "Demonstrated a mathematical model for warehouse space optimization, showcasing substantial space savings and associated cost reductions for warehouse managers.",
        "Established an electronic inventory management system, enabling real-time tracking of all package details, including size, weight, box regularity, and item classification to enhance warehouse parcel management.",
        "Upon package data entry, our space optimization system rapidly generates loading details with visual explanations, outlining efficient stacking strategies and sequencing of goods.",
      ],
      image_gallery: [],
      verification: "",
      verification_link: "",
    },
    {
      project_name: "RoomLink",
      link: "https://docs.google.com/presentation/d/1qpgZeGemWX1NxNNyjrUNlE8jUdqQCDZY_5sBrn3G_gg/edit?usp=sharing",
      date: "Nov 2023 – Dec 2023",
      role: "Product Designer, Technical Support",
      techniques: ["Figma"],
      short_description:
        "RoomLink is a pioneering accommodation service dedicated to helping international students effortlessly secure verified housing, tailored to their preferences through advanced algorithms and a commitment to a seamless and secure experience.",
      tasks: [
        "Leveraged <strong>Figma</strong> to design an intuitive UI that guides users through a clear and concise product flow for immediate trial, featuring an AI chatbot for tailored apartment recommendations, strategic tagging to highlight property features, and 3D blueprints to meet customer demands with a user-friendly interface.",
        "Engineered the product's core functionality to enhance the quality of apartment search and recommendations using AI's machine learning algorithms, coupled with web scraping for data collection and human curation for precision, all within a one-stop service platform to minimize user navigation.",
      ],
      image_gallery: [
        "https://github.com/JiayingYu152/image-and-files/raw/e04654c7a2b4022cb96aa29a89b18505cd48d7ae/roomlink_1.png",
        "https://github.com/JiayingYu152/image-and-files/raw/e04654c7a2b4022cb96aa29a89b18505cd48d7ae/roomlink_2.png",
        "https://github.com/JiayingYu152/image-and-files/raw/e04654c7a2b4022cb96aa29a89b18505cd48d7ae/roomlink_3.png",
        "https://github.com/JiayingYu152/image-and-files/raw/e04654c7a2b4022cb96aa29a89b18505cd48d7ae/roomlink_4.png",
      ],
      verification: "",
      verification_link: "",
    },
  ],
};
